/**
 * Created by michalfrystacky on 12/18/16.
 */
let LOAD_CONTENT = 'LOAD_CONTENT',
    API_REQUEST_RESTAURANTS = 'API_REQUEST_RESTAURANTS',
    API_REQUEST_SUCCESS = 'API_REQUEST_SUCCESS',
    API_REQUEST_FAILURE = 'API_REQUEST_FAILURE';

const types = {
    LOAD_CONTENT,
    API_REQUEST_RESTAURANTS,
    API_REQUEST_SUCCESS,
    API_REQUEST_FAILURE
};


export default types;